name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test_gem:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.6
          bundler-cache: true

      - name: Run tests
        run: |
          bundle exec rspec

  test_examples:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    env:
      CADENCE_HOST: proxy
      CADENCE_PORT: 6666

    steps:
      - uses: actions/checkout@v3

      - name: Start dependencies
        run: |
          docker-compose \
            -f examples/docker-compose.yml \
            up -d

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.6

      - name: Bundle install
        run: |
          cd examples && bundle install --path vendor/bundle

      - name: Wait for dependencies to settle
        run: |
          sleep 10

      - name: Register Domain
        run: |
          cd examples && bin/register_domain ruby-samples

      - name: Wait for domain to settle
        run: |
          sleep 10

      - name: Boot up worker
        run: |
          cd examples && bin/worker &

      - name: Run RSpec
        run: |
          cd examples && bundle exec rspec